### ISSUE TITLE
How should I use it?

### ISSUE THREAD

**Issue by shunyj** [Wavechaser/NamiColor#2]
I put the downloaded .c file into the specified location, but it doesn't seem to have any effect

**Comment by Wavechaser** [comment]
Although DCTLs use C grammar for scripting, Resolve itself will only read files with .dctl extensions.

You could attempt to rename the .c file, or you could directly visit the [releases page](https://github.com/Wavechaser/NamiColor/releases/tag/v3.0) for a ready-to-use version.
